### ISSUE TITLE
cloud-init failing

### ISSUE THREAD

**Issue by courtschuett** [AWSinAction/code2#17]
Trying to use the script in Chapter 5 and it kept failing.  Copied the yaml out and started it manually in cloud formation UI and turned off Roll Back on Failure.  It is still failing, but the VM loads successfully.  However, in the cloud-init, I see these errors:

Cloud-init v. 0.7.6 running 'modules:config' at Mon, 03 Jun 2019 00:10:05 +0000. Up 7.22 seconds.
Loaded plugins: priorities, update-motd, upgrade-helper

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn-main/latest
Could not retrieve mirrorlist http://repo.us-east-2.amazonaws.com/latest/main/mirror.list error was
12: Timeout on http://repo.us-east-2.amazonaws.com/latest/main/mirror.list: (28, 'Connection timed out after 5000 milliseconds')
Jun 03 00:10:21 cloud-init[2491]: util.py[WARNING]: Package upgrade failed
Jun 03 00:10:21 cloud-init[2491]: cc_package_update_upgrade_install.py[WARNING]: 1 failed with exceptions, re-raising the last one
Jun 03 00:10:21 cloud-init[2491]: util.py[WARNING]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) failed
Cloud-init v. 0.7.6 running 'modules:final' at Mon, 03 Jun 2019 00:10:22 +0000. Up 23.41 seconds.
+ export IPSEC_PSK=12345
+ IPSEC_PSK=12345
+ export VPN_USER=12345
+ VPN_USER=12345
+ export VPN_PASSWORD=12345
+ VPN_PASSWORD=12345
+ bash -ex
+ curl -s https://raw.githubusercontent.com/AWSinAction/code2/master/chapter05/vpn-setup.sh
+ /opt/aws/bin/cfn-signal -e 0 --stack vpn --resource EC2Instance --region us-east-2
Unknown error signaling EC2Instance
Jun 03 00:17:46 cloud-init[2606]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Jun 03 00:17:46 cloud-init[2606]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Jun 03 00:17:46 cloud-init[2606]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 0.7.6 finished at Mon, 03 Jun 2019 00:17:46 +0000. Datasource DataSourceEc2.  Up 467.85 seconds
[root@ip-172-31-16-113 log]#

**Comment by michaelwittig** [comment]
hi! Do you select a subnet with a route to the Internet (either via a NAT Gateway or an Internet Gateway)?

**Comment by courtschuett** [comment]
Sorry, I did, but it wasn't auto assigning a public IP.  Could get it to work by adding an Elastic but fixed with auto assigning.  Thanks!
