### ISSUE TITLE
Add chapter names

### ISSUE THREAD

**Issue by ikamensh** [AWSinAction/code2#39]
When browsing some  time after reading the book,  it's a bit hard to navigate the repository. Would it be possible to name folders e.g. "chapter06_IAM" or similar?

**Comment by michaelwittig** [comment]
Hi @ikamensh 

Thanks for your feedback! Unfortunately, changing the folders now will create problems because the URLs are in the printed book. But we will consider this in the next edition :)

As a workaround, what do you think about an "index" in the main README.md file of the repo?

**Comment by ikamensh** [comment]
Yes, I think it would serve well before 3rd edition! Thanks for writing ✍️

**Comment by michaelwittig** [comment]
Sounds good.

You can find the overview here: https://github.com/AWSinAction/code2#code-exampless-by-chapter
