### ISSUE TITLE
book section 5.4.2 causes "Environment must have instance profile associated with it."

### ISSUE THREAD

**Issue by UzK98fYoE** [AWSinAction/code2#41]
Steps to reproduce:

1. follow section 5.4.2
2. see "Environment must have instance profile associated with it."

**Comment by UzK98fYoE** [comment]
At this point in the book, you're supposed to be using the root user on a new AWS account. I was using an IAM user on my own account, which caused this issue.

**Comment by michaelwittig** [comment]
Unfortunately, Elastic Beanstalk introduced a backward-incompatible (aka breaking) change that no longer allows environments without an [instance profile](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles-instance.html). Therefore, the example is broken, and we can not offer an easy fix.

I added this to the errata.
