### ISSUE TITLE
Chapter16 

### ISSUE THREAD

**Issue by mis3250** [AWSinAction/code2#49]
Dear Michael:

Since AWS updates node.js with new versions:

64bit Amazon Linux 2 v5.4.5 running Node.js 12
64bit Amazon Linux 2 v5.4.5 running Node.js 14

The image processing template in your book (chapter 16) is not working well.

Could you please update the template if possible?

Thank you very much!

Zhengzhong

**Comment by michaelwittig** [comment]
Thanks for reporting this issue.

I updated to `64bit Amazon Linux 2018.03 v4.14.1 running Node.js`.

We have some dependencies that likely do not work out-of-the-box on AL 2 here: https://github.com/AWSinAction/code2/blob/master/chapter16/worker/.ebextensions/worker.config#L3-L5
