### ISSUE TITLE
Figure 4.2 From JIML blueprint to infrastructure 

### ISSUE THREAD

**Issue by yuxh** [AWSinAction/code2#50]
I think right part of the figure is not correct, DNS only depends on CDN not LB ,like  Figure 4.3

**Comment by michaelwittig** [comment]
Hi! I', not sure if I get your point. Figure 4.3 says DNS references CDN. CDN references LB and Bucket.

The DNS entry points to the CDN endpoint. Depending on the path of the request, the CDN either routes to the load balancer or the bucket with static assets.

**Comment by yuxh** [comment]
I mean DNS in Figure 4.2 seems to depend on  load balancer

**Comment by michaelwittig** [comment]
Oh, now I see it. You are right. In figure 4.2, the arrow from DNS to Load balancer should be from CDN to Load balancer.

We will update the errata accordingly soon.
