### ISSUE TITLE
Etherpad environment fails

### ISSUE THREAD

**Issue by ammaratef45** [AWSinAction/code2#58]
When creating an environment using Elastic Beanstalk The following errors happen:

1- SolutionStackName is a deprecated platform, using `[1]` instead of `[0]` in the command below fixes that (basically using Amazon Linux 2)
`aws elasticbeanstalk list-available-solution-stacks --output text --query "SolutionStacks[?contains(@, 'running Node.js')] | [1]"`

2-`Unknown or duplicate parameter: NodeCommand`

When I unzipped the code, added ProcFile with content `web: npm start` the problem went away, need to update the hosted S3 file to reflect that

**Comment by michaelwittig** [comment]
Hi @ammaratef45 Are you referring to Section 5.4 ?

**Comment by ammaratef45** [comment]
Yes

**Comment by michaelwittig** [comment]
I see. I'm sorry you were running into issues. We added a hint to our errata a couple of years ago but it is very easy to not notice the errata (this includes myself).

> Section 5.4: Elastic Beanstalk example broken
> Unfortunately, Elastic Beanstalk introduced a backward-incompatible (aka breaking) change that no longer allows environments without an [instance profile](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles-instance.html). Therefore, the example is broken, and we can not offer an easy fix.
>
> Printed book page 145 - 2020-07-30

You can find a link to the errata on the [books page](https://www.manning.com/books/amazon-web-services-in-action-second-edition) under resources box (I don't see the box on my mobile device, desktop only).

Your error is different but it might still not work as expected. 

PS: We are working in the 3rd edition at the moment and we plan to change chapter 5 quiet heavily.

**Comment by ammaratef45** [comment]
Oh thanks, will check that
